### ISSUE TITLE
Lvl 69 character 

### ISSUE THREAD

**Issue by Khope52** [PyrexBLJ/blsdk-mods#10]
I bought bl2 and all dlcs and followed the instructions but when I did my character is lvl 69 and everything else is 80

**Comment by PyrexBLJ** [comment]
its either a hexedited/bl2fix capped executable from the past or one of the level cap increase dlc's isn't purchased or installed

**Comment by Khope52** [comment]
> its either a hexedited/bl2fix capped executable from the past or one of the level cap increase dlc's isn't purchased or installed

I fixed it was missing some dlc

**Comment by Khope52** [comment]
Thank you the game is fun
