### ISSUE TITLE
RougeLands-Mad Mike Boss arena

### ISSUE THREAD

**Issue by RvGIced** [PyrexBLJ/blsdk-mods#2]
On the Mad Mike boss arena there is a Weapon chest with 2 small ammo chest on the top area that are to close to each other. I got hit with a grenade and well under the weapon chest when it opened. I couldn't get out even after getting into Fight for Your Life and had to quit.

**Comment by PyrexBLJ** [comment]
this is a vanilla game issue, not much i can do to fix that.
