### ISSUE TITLE
Download Link not working

### ISSUE THREAD

**Issue by richyrich9707** [PyrexBLJ/blsdk-mods#4]
I was able to download the other 2 mods needed for Roguelands. But couldn't download the Roguelands mod it self.

**Comment by x2agentsF** [comment]
The link is not working for me either.

**Comment by sebastianwhiffen** [comment]
same here

**Comment by Redekye** [comment]
i was able to get it to download by right clicking the "download link" and clicking "open in new window", then click the reload in the top left and it should download

**Comment by sebastianwhiffen** [comment]
@Redekye similarly I was able to get this working by pasting the actual download request straight into the browser lookup

[working download link as of 3/03/2024 8:50 pm central time ](https://raw.githubusercontent.com/PyrexBLJ/blsdk-mods/main/RoguelandsGamemode/RoguelandsGamemode.rar)

below is the HAR playback from f12 chrome dev tools. if you load it up you can see a 302 before the 200. this doesnt happen when downloading other things

seems to be an issue with the site tbh doubt its related to the mod itself

[bl-sdk.github.io.zip](https://github.com/PyrexBLJ/blsdk-mods/files/14471506/bl-sdk.github.io.zip)

**Comment by PyrexBLJ** [comment]
download link has been fixed, should be working now.
