### ISSUE TITLE
Keps loading into Fight for Sanctuary - Roguelands

### ISSUE THREAD

**Issue by markdgoodrich** [PyrexBLJ/blsdk-mods#7]
I have the latest version of the pythonsdk, and all the pre-req mods installed. I select to start with a lvl 30 character, and it keeps putting me in the Fight for Sanctuary DLC instead of the mod itself.

I've checked the videos and the console to make sure I have everything configured correctly. I even get the Roguelands pop-up text when I enable the mod.

Any ideas what could be going on?

![RoguelandsConsole](https://github.com/PyrexBLJ/blsdk-mods/assets/24979274/ae2d0c24-2a2b-4a4a-a2a1-b0f77c5cecbe)

**Comment by PyrexBLJ** [comment]
is the mod made by juso in the mods menu? if it is thats the wrong roguelands mod. need this one https://github.com/PyrexBLJ/blsdk-mods/blob/main/RoguelandsGamemode/RoguelandsGamemode.rar

**Comment by markdgoodrich** [comment]
oh good catch! not sure how i downloaded Juso's, but that is likely the culprit. 
FWIW, the link to Roguelands in your ReadMe seems dead: https://github.com/PyrexBLJ/blsdk-mods/tree/main/Roguelands

**Comment by markdgoodrich** [comment]
That did it! thank you!

**Comment by PyrexBLJ** [comment]
oh, good catch on that dead link, ill fix that
